= Darwin

Darwin is an open-source, extensible, and modular evolution simulator. It's primarily designed for evolution of entities based on neural networks.

Designed as an evolution simulation, Darwin houses a full-fledged evolution simulation framework, comprising vital components for evolution simulation.If you want to simulate evolution of a custom entity in your own defined environment, as Darwin's extension, Darwin provides the framework for making the task least redundant.

Darwin utilizes genetic algorithms for simulating evolution. The extensions, if needed, use OpenNN for neural networks. A powerful game engine called cocos2d-x is used for visualization and integration with the physics engine, Chipmunk. SQLite3 is used as a database engine, while FlatBuffers is used for serialization/deserialization of data to be stored as BLOB (Binary Large OBject) in the local database.
Overall, it’s a solid foundation on top of which the whole evolution ecosystem runs. It is mostly written in C++ and C.

== Features

* Simulate evolution of custom entities
* Define custom environment for simulation
* Save progress of evolution after every generation
* Control vital variables of evolution
** Mutation rate
** Speed
** Population size
* Web Portal
** Track sessions
** Track generations
** View scores at every saved state