#ifndef __FLAPPERS_CONSTANTS_H__
#define __FLAPPERS_CONSTANTS_H__

#define PIPE_HEAD_HEIGHT 24
#define PIPE_BODY_HEIGHT 296
#define PIPE_BODY_WIDTH 52
#define BASE_HEIGHT 112
#define PIPE_MIDDLE_SPACE 150
#define FLAPPER_WIDTH 34
#define FLAPPER_HEIGHT 24

#endif // __FLAPPERS_CONSTANTS_H__