= Creating Custom Extensions

The process of creating a custom extension is designed to be easy, simple, yet flexible and powerful.

The following steps are laid out to help you create your own extension right now!

> Throughout the entire documentation, leading slashes indicate the root of the Darwin's repository.

== Naming Convention

Pick a name for your extension. It's advised to use a consistent naming convention wherever appropriate. Naming guidelines will be provided whenever the extension name is involved.

== Step 1: Laying out the Directories

=== Source Files

Create a directory for holding your source code inside `/extensions`, with your extension's name. It's conventional to use snake case. If your name is called "Lorem Ipsum", the directory name will be "lorem_ipsum".

Inside it, by convention, create a directory called `classes` to hold your C++ classes. This is because the `/CMakeLists.txt` file compiles the C++ files in this directory. If you want to have an unconventional directory structure, feel free to modify the `/CMakeLists.txt` to include the source files in your extension.

By now, the directory structure should look like this:

....
├─ extensions/
│  ├─ <EXTENSION_NAME>/
│  │  ├─ classes/
....

Replace _<EXTENSION_NAME>_ with the name of your extension.

=== Header Files

Create a directory with the name of your extension (in snake case) in `/includes/extensions`. This is where you'll keep your header files. The `/includes` directory is set in the `/CMakeLists.txt` to be automatically searched for header files.

=== Resources

If you're creating an extension based on cocos2d-x, the resources, such as images, sprite sheets, audio, fonts, etc will reside in the `/resources` directory. To keep the contents organized, each extension will have its own directory.

Create a directory in `/resources` with the snake-cased version of your extension's name. The `/resources` directory, along with its content, will be automatically included in Darwin's executable as per the `/CMakeLists.txt` file.

== Step 2: Creating AppDelegate and MainScene class

This step can be safely ignored if your extension isn't based on cocos2d-x.

Inside `/extensions/<EXTENSION_NAME>/classes` directory, create two files for two classes - `AppDelegate` and `MainScene`. It's conventional to use pascal casing for the file names.

Please follow cocos2d-x documentation for defining the classes.

== Step 3: Adding Extension to the Web Portal

To add your extension to the web portal, you need to add an entry to the `extensions` table in the `/portal/database/database.db` database. It's an SQLite database and can be modified with any standard SQLite database reader. It's conventional to use snake case in the entry of your extension's name.

It's advised to create an entry for your extension through seeding.Please follow Laravel's documentation for seeders.

== Step 4: Making the Extension Runnable Through the Control Panel

To make it possible to run the extension through the control panel, you need to add a piece of code in the `ControlPanelFrame::StartEvolution` method of the `/src/ControlPanel.cpp` file.

Here's what the segment of code may look like, where <EXTENSION_NAME> is the name of your extension in Pascal Case:

[source]
----
if (extensionName == "Jumper")
{
    Jumper::AppDelegate app;
    cocos2d::Application::getInstance()->run();
}
else if (extensionName == "Wheels")
{
    Wheels::AppDelegate app;
    cocos2d::Application::getInstance()->run();
}
else if (extensionName == "<EXTENSION_NAME>")
{
    <EXTENSION_NAME>::AppDelegate app;
    cocos2d::Application::getInstance()->run();
}
----

The example above involves an extension based on cocos2d-x. Your extension can be based on anything you desire.
