= Flappers

Flappers are sprites that are spawned mid-air at the beginning of the game. They are constantly pulled downwards through a simulated gravitational force and can regain height through a series of small jumps (flaps). A number of flapper units are spawned at the beginning of the game and each has a neural network attached to it. In the beginning, flappers have random weights & biases in their neural networks.

== Pipes

Pipes are added to the scene at a fixed time interval. Ratio of the top and the bottom pipe heights are sequentially chosen from a repeating series of values, leading to a fixed set of pipe obstacles that each flapper must navigate through. The same series of pipes have been used for all training sessions in order to ensure comparable scores across generations and sessions.

== Tracks

The cars spawned in the Wheels training sessions move through a curved race track. A car that hits the boundaries of any part of the road is considered to be a failure. Successful cars can move past the various curves in the track without hitting the boundaries. The same track has been used for all training sessions to ensure comparable scores across generations and sessions.

== Neural Networks

*Input:* Each neural network receives four numerical input parameters from the Flapper that it is attached to:

* Horizontal distance of the flapper to rightward pipe
* Vertical distance of the flapper to rightward top pipe
* Vertical distance of the flapper to rightward bottom pipe
* Vertical velocity of the flapper

*Output:* A number ranging from 0 to 1. If it's greater than 0.5, the number is interpreted as a decision to flap(jump).

== Scoring System

Flappers die when they hit an obstacle - i.e. the various pipes, the ceiling, or the ground/base. Success is determined by the time, in seconds (accurate to the nearest millisecond), which a flapper manages to stay alive. Highly successful units can navigate all the pipe obstacles in its path without failing. 