= Jumpers

*Jumpers* is an extension of Darwin intended to depict the behavior of real-world instinctual behavior of organisms, especially ones that involve quick reflexes. Here, organisms (called jumpers) will have one goal - to jump and avoid obstacles heading their way. To detect obstacles, they have a sensor attached to their front. Each jumper will have to jump to avoid the obstacles or get hit and killed.

This is an extension where an experimental feature of Darwin - parallel testing - has been implemented. Parallel testing involves concurrently testing a specific population in various ways. As for jumpers, the same population is spawned thrice and each set is tested with an obstacle of a different speed. The score of each member is the sum of all the scores of its instances.

== Jumper

Jumpers, which are depicted by sprites, can only jump to a certain height. They cannot move sideways. They have a sensor, which they can use to sense obstacles in front of them. Before having to cooldown, they can jump in a short burst, by exerting an upward impulse, to avoid obstacles. Otherwise they’ll get killed when hit by one. All instances of jumpers having the same chromosomes is referred to as a *Jumper Group*.

== Obstacles

Obstacles are depicted by balls, which move towards the jumpers with a fixed velocity. Parallel testing is done in the extension, as mentioned above, where obstacles move at different speeds in each part of the test.

== Neural Networks

*Input:* A number between 0 and 1, indicating the distance between the jumper and the obstacle. Higher the value, closer the obstacle. The value is calculated by a technique known as ray tracing. Ray tracing is made possible by the physics engine, Chipmunk.

*Output:* A number ranging from 0 to 1. If it’s greater than 0.5, it’s interpreted as the decision to jump.

== Scoring System

The number of times a jumper jumps is recorded. If the jumper stays alive till the end of the generation, the score is equal to the reciprocal of the number of jumps. Otherwise it’s equal to 0. Since the members of a jumper group have the same chromosomes, the sum of the scores of the members is considered. The score of an ideal jumper group is x, where x is the number of members in that group. This is because an ideal jumper should only jump once to avoid one obstacle.